### ISSUE TITLE
Formidable Form option not visible in BWS Captcha Pro

### ISSUE THREAD

**Issue by jwahlin** [Strategy11/formidable-math-captcha#3]

**Comment by jonato1** [comment]
There may be some issues here that are related: https://formidablepro.com/help-desk/formidable-math-doesnt-work-with-formidable-pro-the-option-doesnt-show/

**Comment by jwahlin** [comment]
Yeah, I still need to make the add-on compatible with the BWS Pro version of math captcha. Unfortunately they use different hooks for each of their versions so it's kind of annoying to integrate with all three of their versions.
